export const TODO_ADD = 'TODO_ADD';
export const TODO_REMOVE = 'TODO_REMOVE';
export const TODO_SET_FILTER = 'TODO_SET_FILTER';
export const TODO_UPDATE = 'TODO_UPDATE';
export const TODO_GET_ITEMS = 'TODO_GET_ITEMS';
export const TODO_GET_ITEMS_SUCCESS = 'TODO_GET_ITEMS_SUCCESS';
